### ISSUE TITLE
Update version number (currently v0.3.2)

### ISSUE THREAD

**Issue by tylermorganwall** [jefferis/readobj#11]
I recently was using readobj and wondering why my local version of the code wasn't returning texcoords when the code on Github said it should be, and realized there was a change even though the version numbers were the same. I'm just opening this issue to recommend you update the version number so people are aware the code has changed.

**Comment by jefferis** [comment]
Thanks @tylermorganwall! The truth is I stalled merging #8 which was a complex PR by @trevorld and me. The intention was to release when that was integrated.

**Comment by trevorld** [comment]
@jefferis Any reason not to update to a development version number?  [Hadley Wickham prefers v0.3.2.9000](https://r-pkgs.org/description.html#version) while I prefer v0.4.0-1 ([semantic versioning](https://semver.org/) style development numbers although this would force your CRAN release to be v0.4.1 instead of v0.4.0).

**Comment by trevorld** [comment]
closed by d89392a211b7a82cf1f9d

**Comment by jefferis** [comment]
@trevorld updated version just submitted to CRAN.
